CREATE DATABASE IF NOT EXISTS stanza;
USE stanza;

DROP TABLE IF EXISTS text_genres;
DROP TABLE IF EXISTS reading_logs;
DROP TABLE IF EXISTS embeddings;
DROP TABLE IF EXISTS texts;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS password_resets;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    birthdate DATE NOT NULL,
    gender ENUM('male', 'female', 'other') NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    role ENUM('reader', 'author', 'admin') NOT NULL DEFAULT 'reader'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE texts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    author_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    read_count INT DEFAULT 0,
	description VARCHAR(255) NOT NULL,
	category ENUM('book', 'poetry', 'story') NOT NULL,
    cover_image VARCHAR(255) DEFAULT NULL,
    visibility ENUM('public', 'private') NOT NULL DEFAULT 'public',
    language ENUM('enus', 'ptbr', 'es'),
    favorites INT DEFAULT 0,

    FOREIGN KEY (author_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE embeddings (
    id INT PRIMARY KEY,
    embedding BLOB NOT NULL,
    FOREIGN KEY (id) REFERENCES texts(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE reading_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    reader_id INT NOT NULL,
    text_id INT NOT NULL,
    started_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    time_spent_seconds INT NOT NULL,

    FOREIGN KEY (reader_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (text_id) REFERENCES texts(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE genres (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE text_genres (
    text_id INT NOT NULL,
    genre_id INT NOT NULL,
    PRIMARY KEY (text_id, genre_id),
    FOREIGN KEY (text_id) REFERENCES texts(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES genres(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


INSERT IGNORE INTO genres (name) VALUES
('Fantasia'),
('Drama'),
('Romance'),
('Terror'),
('Ficção Científica'),
('Suspense'),
('Aventura'),
('Mistério'),
('Poesia Lírica'),
('Realismo Mágico'),
('Comédia'),
('Distopia'),
('#romance'),
('#romantico'),
('#amor'),
('#love'),
('#romcom'),
('#comediaromantica'),
('#slowburn'),
('#friends2lovers'),
('#enemiestolovers'),
('#friendswithbenefits'),
('#firstlove'),
('#younglove'),
('#forbiddenlove'),
('#truelove'),
('#secondchance'),
('#childhoodfriends'),
('#drama'),
('#angst'),
('#emotional'),
('#feelings'),
('#heartbreak'),
('#superacao'),
('#segredos'),
('#mentiras'),
('#traicao'),
('#amizade'),
('#familia'),
('#conflitos'),
('#plotwist'),
('#twist'),
('#surpresa'),
('#misterio'),
('#mystery'),
('#suspense'),
('#thriller'),
('#investigacao'),
('#segredo'),
('#desaparecimento'),
('#enigma'),
('#crime'),
('#conspiracao'),
('#fantasia'),
('#fantasy'),
('#magia'),
('#magic'),
('#reino'),
('#kingdom'),
('#princesa'),
('#principe'),
('#rainha'),
('#rei'),
('#dragao'),
('#fadas'),
('#bruxas'),
('#feiticeiros'),
('#profecia'),
('#guerra'),
('#aventura'),
('#mitologia'),
('#fantasiamedieval'),
('#paranormal'),
('#sobrenatural'),
('#vampiros'),
('#vampire'),
('#lobisomem'),
('#werewolf'),
('#fantasmas'),
('#ghosts'),
('#demonios'),
('#anjos'),
('#imortais'),
('#supernatural'),
('#teenfiction'),
('#youngadult'),
('#juvenil'),
('#escola'),
('#colegio'),
('#highschool'),
('#faculdade'),
('#universidade'),
('#college'),
('#popular'),
('#nerd'),
('#novato'),
('#adolescencia'),
('#comingofage'),
('#comedia'),
('#humor'),
('#funny'),
('#comedy'),
('#situacoesengracadas'),
('#caos'),
('#sarcasmo'),
('#acao'),
('#action'),
('#adventure'),
('#batalha'),
('#heroi'),
('#heroina'),
('#missao'),
('#jornada'),
('#sobrevivencia'),
('#viagem'),
('#exploracao'),
('#ficcaocientifica'),
('#sciencefiction'),
('#scifi'),
('#futuro'),
('#espaco'),
('#aliens'),
('#extraterrestres'),
('#distopia'),
('#utopia'),
('#tecnologia'),
('#robos'),
('#viagemnotempo'),
('#timeTravel'),
('#terror'),
('#horror'),
('#medo'),
('#assustador'),
('#creepy'),
('#casaassombrada'),
('#lendaurbana'),
('#fanfic'),
('#fanfiction'),
('#fandom'),
('#crossover'),
('#alternateuniverse'),
('#au'),
('#oc'),
('#originalcharacter'),
('#reader'),
('#imagines'),
('#friendstolovers'),
('#strangers2lovers'),
('#fakeDating'),
('#forcedproximity'),
('#oppositesattract'),
('#loveTriangle'),
('#onlyonebed'),
('#secretrelationship'),
('#brasil'),
('#saopaulo'),
('#riodejaneiro'),
('#newyork'),
('#londres'),
('#paris'),
('#cidadepequena'),
('#smalltown'),
('#praia'),
('#interior'),
('#cidadegrande'),
('#medieval'),
('#primeirapessoa'),
('#terceirapessoa'),
('#multiplospov'),
('#pov'),
('#diario'),
('#cartas'),
('#mensagens'),
('#chatfic'),
('#shortstory'),
('#oneshot'),
('#serie'),
('#trilogia'),
('#completed'),
('#ongoing');

CREATE TABLE password_resets (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  token_hash CHAR(64) NOT NULL,
  expires_at DATETIME NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  used TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_password_resets_token_hash (token_hash),
  KEY idx_password_resets_user_id (user_id),
  CONSTRAINT fk_password_resets_user_id
    FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
